<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_currency</name>
   <tag></tag>
   <elementGuidId>9b34003a-c3f1-4150-9ba3-21dc97fd3b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'currency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#currency</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1e7fa647-6a6e-43fc-95b6-e568288bd485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>17100b3d-c5f4-4247-9f63-7b2c2da1bc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>cc951daf-26b6-4450-ac52-b9460006b255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>a5cfc80a-5365-4b16-8f88-ba0bb70693a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>13b25b2f-61e2-41bc-967c-d02ee67286e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	</value>
      <webElementGuid>5338c45d-0154-40c5-90d0-69250bb9d892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e1c0eb23d443eb950ab0f67aef3ea842</value>
      <webElementGuid>2062181d-b8ad-4893-a646-7dc5744e1688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'currency']</value>
      <webElementGuid>f19c324d-cfb7-48f2-b453-40806d593648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'currency']</value>
      <webElementGuid>2c3e0faf-3a6d-41be-b2ee-b9e95abc616d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and @id = 'currency' and (text() = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	' or . = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	')]</value>
      <webElementGuid>9e24f7a5-b753-42b4-8b7b-1a472167fc63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
