<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TransactionFailed</name>
   <tag></tag>
   <elementGuidId>b7c6855f-038d-49ea-ae52-f5af7aae0a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' error ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Transaction Failed. You can not withdraw amount more than the balance.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6239b5ad-b59d-47dd-a846-84194a97e8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error ng-binding</value>
      <webElementGuid>7e9cf68a-5790-4d26-8cbe-611fa481cbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>e12cd186-a4ad-46c0-bb22-418fd4fa65d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction Failed. You can not withdraw amount more than the balance.</value>
      <webElementGuid>4acb292d-57f0-4724-a14d-e256c72539ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ddcb390cc1cb26ed48106ba9c2bfbda0</value>
      <webElementGuid>b09dfca7-61a6-43e9-a563-e12e78171f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' error ')]</value>
      <webElementGuid>d2e9744e-3649-4f6b-8a82-1febf0f6f358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' error ')]</value>
      <webElementGuid>bd98fade-8f2b-4ef2-9f9e-a600ddb902ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transaction Failed. You can not withdraw amount more than the balance.' or . = 'Transaction Failed. You can not withdraw amount more than the balance.')]</value>
      <webElementGuid>eba405db-69f6-4d18-b52d-472de58e6913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
